/** Digital twin catalog — honest public horizon. SSOT for conrrad.org information architecture. */

export type HonestyStatus =
  | 'stable'
  | 'public'
  | 'preview'
  | 'early_access'
  | 'in_development'
  | 'research'
  | 'informational'
  | 'planned'

export type Layer = 'product' | 'technology' | 'organization' | 'ecosystem'

export type ModuleDef = {
  id: string
  layer: Layer
  title: string
  blurb: string
  status: HonestyStatus
  /** What a visitor can rely on today (honest). */
  today: string[]
  /** Explicitly not ready — shown, never sold as live. */
  notYet: string[]
  /** Optional external truth. */
  links?: { label: string; href: string }[]
}

export const STATUS_LABEL: Record<HonestyStatus, string> = {
  stable: 'Stable',
  public: 'Public',
  preview: 'Preview',
  early_access: 'Early Access',
  in_development: 'In Development',
  research: 'Research',
  informational: 'Informational',
  planned: 'Planned',
}

export const STATUS_HINT: Record<HonestyStatus, string> = {
  stable: 'In use with evidence / frozen contracts.',
  public: 'Usable with known gaps; expect change.',
  preview: 'Visible / path exists; product UI incomplete.',
  early_access: 'Shell or partial capability; not production UX.',
  in_development: 'Active build; not visitor-ready.',
  research: 'Spec / exploration — not a shipped product.',
  informational: 'Documented intent; limited runtime surface.',
  planned: 'On the horizon; no honest claim of readiness.',
}

export const LAYERS: { id: Layer; title: string; blurb: string; path: string }[] = [
  {
    id: 'product',
    title: 'Product',
    blurb: 'What operators will do inside CONRRAD.',
    path: '/product',
  },
  {
    id: 'technology',
    title: 'Technology',
    blurb: 'Runtime, governance, evidence, and protocols.',
    path: '/technology',
  },
  {
    id: 'organization',
    title: 'Organization',
    blurb: 'Mission, principles, people, and public record.',
    path: '/organization',
  },
  {
    id: 'ecosystem',
    title: 'Ecosystem',
    blurb: 'Docs, SDK, APIs, and ways to build or contribute.',
    path: '/ecosystem',
  },
]

/** Full horizon — day 1 visibility. Statuses are deliberately conservative. */
export const MODULES: ModuleDef[] = [
  // —— Product ——
  {
    id: 'projects',
    layer: 'product',
    title: 'Projects',
    blurb: 'Create and manage workspaces for governed work.',
    status: 'early_access',
    today: ['Navigation shell', 'Surface card'],
    notYet: ['Create/list projects UI', 'Persistence'],
  },
  {
    id: 'workspace',
    layer: 'product',
    title: 'Workspace',
    blurb: 'Active habitat and runtime context.',
    status: 'early_access',
    today: ['Shell reserved'],
    notYet: ['Bind runtime context', 'Multi-workspace'],
  },
  {
    id: 'execution',
    layer: 'product',
    title: 'Execution',
    blurb: 'Run tasks against runtime.conrrad.org.',
    status: 'preview',
    today: ['Public runtime health path certified', 'Product shell'],
    notYet: ['First-class Run UI', 'Streaming job console'],
  },
  {
    id: 'packages',
    layer: 'product',
    title: 'Packages',
    blurb: 'Execution Packages from the planning runtime (Freeze C0).',
    status: 'preview',
    today: ['Package model', 'Scheduler Freeze C0', 'Evidence regenerators'],
    notYet: ['In-app package board'],
  },
  {
    id: 'evidence',
    layer: 'product',
    title: 'Evidence',
    blurb: 'Regenerable receipts and audit trails.',
    status: 'preview',
    today: ['Repo evidence trees', 'CERT index scripts'],
    notYet: ['Evidence viewer UI'],
  },
  {
    id: 'certificates',
    layer: 'product',
    title: 'Certificates',
    blurb: 'CERT lifecycle seals.',
    status: 'early_access',
    today: ['CERT stubs / reserved chain'],
    notYet: ['Pass seals after Founder gates', 'Public CERT browser'],
  },
  {
    id: 'agents',
    layer: 'product',
    title: 'Agents',
    blurb: 'Spawn and govern agents under Harlemm.',
    status: 'informational',
    today: ['Architecture & CAS identity'],
    notYet: ['Agent spawn UI', 'Lifecycle console'],
  },
  {
    id: 'memory',
    layer: 'product',
    title: 'Memory',
    blurb: 'Institutional memory fabric.',
    status: 'informational',
    today: ['Infra intent (Redis/Qdrant on Data Plane)'],
    notYet: ['Memory browser UI'],
  },
  {
    id: 'marketplace',
    layer: 'product',
    title: 'Marketplace',
    blurb: 'Providers and plugins under IGE capability registry.',
    status: 'planned',
    today: ['IGE capability model (docs)'],
    notYet: ['Catalog UI', 'Install flow'],
  },
  {
    id: 'deploy',
    layer: 'product',
    title: 'Deploy',
    blurb: 'Control Plane (Vercel) + Runtime (Node-01). ADR-058.',
    status: 'preview',
    today: ['DNS topology documented', 'Runtime path certified'],
    notYet: ['In-app deploy status panel'],
  },
  {
    id: 'logs',
    layer: 'product',
    title: 'Logs / Observability UI',
    blurb: 'Operator-facing observability stream.',
    status: 'planned',
    today: ['Host journals / evidence files'],
    notYet: ['Product log stream UI'],
  },
  {
    id: 'settings',
    layer: 'product',
    title: 'Settings',
    blurb: 'Org, tokens, environment preferences.',
    status: 'early_access',
    today: ['Shell reserved'],
    notYet: ['Prefs form', 'API keys UI'],
  },
  {
    id: 'profile',
    layer: 'product',
    title: 'Profile',
    blurb: 'Account identity and session.',
    status: 'early_access',
    today: ['Preview session stub (email flag)'],
    notYet: ['Real identity provider'],
  },
  {
    id: 'billing',
    layer: 'product',
    title: 'Billing',
    blurb: 'Cloud deploy metering — monetization boundary.',
    status: 'planned',
    today: ['CAS-4 boundary defined (local free / deploy pays)'],
    notYet: ['Self-serve billing', 'Invoices'],
  },

  // —— Technology ——
  {
    id: 'architecture',
    layer: 'technology',
    title: 'Architecture',
    blurb: 'CAS-1 identity, Lab vs Infrastructure, SDK vs Pay boundary.',
    status: 'stable',
    today: ['CAS-1 published', 'ADR-058 deployment spaces'],
    notYet: ['Interactive architecture explorer (beyond static pages)'],
    links: [{ label: 'CAS-1 (GitHub)', href: '/technology/architecture' }],
  },
  {
    id: 'runtime',
    layer: 'technology',
    title: 'Runtime',
    blurb: 'PPE / execution substrate on Node-01.',
    status: 'preview',
    today: ['runtime.conrrad.org health path', 'Cloudflare → nginx → PPE'],
    notYet: ['Public multi-tenant runtime UX'],
    links: [{ label: 'Health', href: 'https://runtime.conrrad.org/__ppe/health' }],
  },
  {
    id: 'harlemm',
    layer: 'technology',
    title: 'Harlemm',
    blurb: 'Host governor — cgroups, namespaces, operational continuity.',
    status: 'in_development',
    today: ['Specification & Lab presence', 'CAS role defined'],
    notYet: ['Productized Harlemm console'],
  },
  {
    id: 'governance',
    layer: 'technology',
    title: 'Governance',
    blurb: 'Enforcing operational continuity and causality.',
    status: 'preview',
    today: ['Freeze protocols', 'Evidence-before-claim culture', 'IGE docs'],
    notYet: ['End-user governance dashboard'],
  },
  {
    id: 'scheduler',
    layer: 'technology',
    title: 'Scheduler',
    blurb: 'Execution package planning runtime (Freeze C0).',
    status: 'stable',
    today: ['Frozen schedule contract', 'Deterministic board render', 'Tests'],
    notYet: ['Public scheduler UI'],
  },
  {
    id: 'memory-fabric',
    layer: 'technology',
    title: 'Memory Fabric',
    blurb: 'Redis / Qdrant / institutional memory plane.',
    status: 'in_development',
    today: ['Data Plane components in Lab/Cluster intent'],
    notYet: ['Public memory APIs for third parties'],
  },
  {
    id: 'evidence-system',
    layer: 'technology',
    title: 'Evidence System',
    blurb: 'Regenerable receipts, seals doctrine, audit trails.',
    status: 'preview',
    today: ['Evidence trees in repo', 'Regen tooling', '$SEAL doctrine (evidence first)'],
    notYet: ['Public evidence browser'],
  },
  {
    id: 'cert-system',
    layer: 'technology',
    title: 'Certificate System',
    blurb: 'CERT-C1 … chain and Founder gates.',
    status: 'early_access',
    today: ['CERT model & reserved seals'],
    notYet: ['Automated public CERT gallery'],
  },
  {
    id: 'ige',
    layer: 'technology',
    title: 'IGE',
    blurb: 'Infrastructure Governance Engine — providers & capabilities.',
    status: 'in_development',
    today: ['IGE specification freeze-ready', 'Kernel stubs'],
    notYet: ['Founder CERT-IGE APPROVED → production promotion'],
  },
  {
    id: 'sdk',
    layer: 'technology',
    title: 'SDK',
    blurb: 'Open-source agent tooling — local free.',
    status: 'public',
    today: ['Public SDK repo / install contract', 'Vocabulary frozen'],
    notYet: ['Complete public quickstart polish'],
    links: [{ label: 'conrrad-sdk', href: 'https://github.com/GRECOITALICO/CONRRAD-SDK' }],
  },
  {
    id: 'apis',
    layer: 'technology',
    title: 'APIs',
    blurb: 'Runtime and control APIs.',
    status: 'early_access',
    today: ['Health endpoints', 'Internal contracts'],
    notYet: ['Versioned public OpenAPI portal'],
  },
  {
    id: 'providers',
    layer: 'technology',
    title: 'Providers',
    blurb: 'Cloud / model / infra providers via IGE.',
    status: 'research',
    today: ['Provider plugin shape (e.g. Cloudflare flag OFF)'],
    notYet: ['Public provider registry'],
  },
  {
    id: 'plugins',
    layer: 'technology',
    title: 'Plugins',
    blurb: 'Extensibility under capability registry.',
    status: 'research',
    today: ['Plugin manifest pattern'],
    notYet: ['Marketplace install'],
  },
  {
    id: 'protocol',
    layer: 'technology',
    title: 'Protocol (KAP)',
    blurb: 'Agent protocol / coordination payloads (CAS-2).',
    status: 'informational',
    today: ['CAS-2 specification'],
    notYet: ['Public protocol playground'],
  },
  {
    id: 'security',
    layer: 'technology',
    title: 'Security',
    blurb: 'Zero-trust intent, Seal Engine, sandboxing (CAS-5).',
    status: 'in_development',
    today: ['CAS-5 spec', 'Deployment space isolation'],
    notYet: ['Public security white-glove portal'],
  },
  {
    id: 'observability',
    layer: 'technology',
    title: 'Observability',
    blurb: 'Telemetry and operational visibility.',
    status: 'in_development',
    today: ['Evidence & journals'],
    notYet: ['Product Observatory UI (superseded by Public App)'],
  },
  {
    id: 'performance',
    layer: 'technology',
    title: 'Performance',
    blurb: 'Continuity metrics — RAM, tokens, latency, uptime.',
    status: 'informational',
    today: ['CAS metric definitions'],
    notYet: ['Public SLO dashboards'],
  },
  {
    id: 'adrs',
    layer: 'technology',
    title: 'ADRs',
    blurb: 'Architecture Decision Records.',
    status: 'stable',
    today: ['ADR corpus in docs/adr'],
    notYet: ['In-site ADR browser with search'],
    links: [{ label: 'ADRs', href: '/ecosystem/documentation' }],
  },

  // —— Organization ——
  {
    id: 'about',
    layer: 'organization',
    title: 'About CONRRAD',
    blurb: 'Infrastructure for governed autonomous AI.',
    status: 'stable',
    today: ['Mission / vision canon', 'This public surface'],
    notYet: [],
  },
  {
    id: 'mission',
    layer: 'organization',
    title: 'Mission',
    blurb: 'Operational continuity with evidence — not raw IQ.',
    status: 'stable',
    today: ['CONRRAD_MISSION_v1'],
    notYet: [],
  },
  {
    id: 'vision',
    layer: 'organization',
    title: 'Vision',
    blurb: 'Economic orchestration for measurable AI work.',
    status: 'stable',
    today: ['Vision canon published'],
    notYet: [],
  },
  {
    id: 'principles',
    layer: 'organization',
    title: 'Principles',
    blurb: 'Architecture First · Evidence Driven · Visible Evolution · Single Web Surface.',
    status: 'stable',
    today: ['Public principles on this site'],
    notYet: [],
  },
  {
    id: 'roadmap',
    layer: 'organization',
    title: 'Roadmap',
    blurb: 'Product trains 1.0 → 2.0+ continuous line of life.',
    status: 'stable',
    today: ['Live roadmap in product + public'],
    notYet: [],
  },
  {
    id: 'milestones',
    layer: 'organization',
    title: 'Milestones',
    blurb: 'Certification and delivery milestones.',
    status: 'early_access',
    today: ['Freeze C0, runtime path, surface public product'],
    notYet: ['Full public milestone timeline UI polish'],
  },
  {
    id: 'founders',
    layer: 'organization',
    title: 'Founders',
    blurb: 'GRECOITALICO — founder of CONRRAD.',
    status: 'informational',
    today: ['Public founder identity: GRECOITALICO', 'GitHub / LinkedIn / YouTube / X'],
    notYet: ['Expanded biography page'],
    links: [
      { label: 'GitHub', href: 'https://github.com/GRECOITALICO' },
      { label: 'LinkedIn', href: 'https://www.linkedin.com/in/grecoitalico/' },
      { label: 'YouTube', href: 'https://www.youtube.com/@ConrradLab' },
      { label: 'X', href: 'https://x.com/conrradlab' },
    ],
  },
  {
    id: 'contributors',
    layer: 'organization',
    title: 'Contributors',
    blurb: 'Open contribution paths.',
    status: 'planned',
    today: ['GitHub issues / PRs welcome in principle'],
    notYet: ['Contributor ladder & recognition program'],
  },
  {
    id: 'community',
    layer: 'organization',
    title: 'Community',
    blurb: 'Gathering points for builders and sponsors.',
    status: 'planned',
    today: ['GitHub as primary channel'],
    notYet: ['Discord', 'Forum'],
  },
  {
    id: 'research',
    layer: 'organization',
    title: 'Research',
    blurb: 'Specs and explorations that are not product claims.',
    status: 'early_access',
    today: ['Research index on this site', 'Nikkole as draft citizen-app'],
    notYet: ['Peer-reviewed publications'],
  },
  {
    id: 'nikkole',
    layer: 'organization',
    title: 'Nikkole',
    blurb: 'Citizen application concept — Universal Cognitive OS (draft). Research · NOT AVAILABLE as product.',
    status: 'research',
    today: ['Design docs under docs/NIKKOLE', 'Mapped as future consumer of CONRRAD'],
    notYet: ['Any shipped Nikkole product', 'Integration certification', 'Public “meet Nikkole” marketing'],
  },
  {
    id: 'publications',
    layer: 'organization',
    title: 'Publications',
    blurb: 'Public writing and notes.',
    status: 'planned',
    today: ['Docs & whitepapers in GitHub'],
    notYet: ['Blog / research notes feed'],
  },
  {
    id: 'whitepapers',
    layer: 'organization',
    title: 'Whitepapers',
    blurb: 'Technical papers (v1/v2; v3 outline).',
    status: 'preview',
    today: ['Whitepapers in docs/', 'Linked from this site'],
    notYet: ['Interactive paper reader'],
    links: [{ label: 'docs/whitepaper', href: '/investors' }],
  },
  {
    id: 'release-notes',
    layer: 'organization',
    title: 'Release Notes',
    blurb: 'Versioned surface and platform notes.',
    status: 'early_access',
    today: ['Changelog on this site'],
    notYet: ['Automated GitHub release sync'],
  },
  {
    id: 'changelog',
    layer: 'organization',
    title: 'Changelog',
    blurb: 'What changed on the public surface.',
    status: 'early_access',
    today: ['Manual changelog entries'],
    notYet: ['Fully automated commit feed'],
  },
  {
    id: 'faq',
    layer: 'organization',
    title: 'FAQ',
    blurb: 'Straight answers for accelerators, investors, and developers.',
    status: 'early_access',
    today: ['Core FAQ page'],
    notYet: [],
  },

  // —— Ecosystem ——
  {
    id: 'documentation',
    layer: 'ecosystem',
    title: 'Documentation',
    blurb: 'CAS, ADRs, runbooks — GitHub today.',
    status: 'preview',
    today: ['Full docs tree on GitHub'],
    notYet: ['In-app docs search'],
    links: [{ label: 'docs/', href: '/ecosystem/documentation' }],
  },
  {
    id: 'github',
    layer: 'ecosystem',
    title: 'GitHub',
    blurb: 'Source of truth for code and evidence.',
    status: 'stable',
    today: ['Public repositories'],
    notYet: [],
    links: [{ label: 'CONRRAD', href: 'https://github.com/GRECOITALICO/CONRRAD-SDK' }],
  },
  {
    id: 'api-portal',
    layer: 'ecosystem',
    title: 'API Portal',
    blurb: 'Developer-facing API entry.',
    status: 'planned',
    today: ['Health URL'],
    notYet: ['OpenAPI explorer'],
  },
  {
    id: 'examples',
    layer: 'ecosystem',
    title: 'Examples',
    blurb: 'Sample agents and demos.',
    status: 'early_access',
    today: ['SDK examples in conrrad-sdk'],
    notYet: ['Curated examples gallery'],
  },
  {
    id: 'tutorials',
    layer: 'ecosystem',
    title: 'Tutorials',
    blurb: 'Guided paths.',
    status: 'planned',
    today: ['Quickstart drafts'],
    notYet: ['Polished tutorial series'],
  },
  {
    id: 'quickstart',
    layer: 'ecosystem',
    title: 'Quick Start',
    blurb: 'Install and run in minutes.',
    status: 'early_access',
    today: ['SDK README quick path'],
    notYet: ['One-page interactive quickstart'],
    links: [{ label: 'SDK README', href: 'https://github.com/GRECOITALICO/CONRRAD-SDK' }],
  },
  {
    id: 'downloads',
    layer: 'ecosystem',
    title: 'Downloads',
    blurb: 'Artifacts and releases.',
    status: 'planned',
    today: ['GitHub releases when published'],
    notYet: ['Download center UI'],
  },
  {
    id: 'docker',
    layer: 'ecosystem',
    title: 'Docker',
    blurb: 'Containerized runtime components.',
    status: 'in_development',
    today: ['Cluster/Lab container use internally'],
    notYet: ['Public official images gallery'],
  },
  {
    id: 'cloud',
    layer: 'ecosystem',
    title: 'Cloud',
    blurb: 'conrrad-cloud deploy target (Pay boundary).',
    status: 'planned',
    today: ['CAS-4 monetization boundary defined'],
    notYet: ['Self-serve cloud signup'],
  },
  {
    id: 'cli',
    layer: 'ecosystem',
    title: 'CLI',
    blurb: 'conrrad developer CLI.',
    status: 'early_access',
    today: ['SDK / repo CLI entrypoints'],
    notYet: ['Unified public CLI docs site'],
  },
  {
    id: 'integrations',
    layer: 'ecosystem',
    title: 'Integrations',
    blurb: 'Third-party systems.',
    status: 'research',
    today: ['Provider plugin research'],
    notYet: ['Integration marketplace'],
  },
  {
    id: 'discord',
    layer: 'ecosystem',
    title: 'Discord',
    blurb: 'Community realtime chat.',
    status: 'planned',
    today: [],
    notYet: ['Server not launched'],
  },
  {
    id: 'forum',
    layer: 'ecosystem',
    title: 'Forum',
    blurb: 'Long-form community.',
    status: 'planned',
    today: [],
    notYet: ['Forum not launched'],
  },
  {
    id: 'newsletter',
    layer: 'ecosystem',
    title: 'Newsletter',
    blurb: 'Release and research updates.',
    status: 'planned',
    today: [],
    notYet: ['List not opened'],
  },
  {
    id: 'blog',
    layer: 'ecosystem',
    title: 'Blog',
    blurb: 'Engineering and product writing.',
    status: 'planned',
    today: [],
    notYet: ['Blog not launched'],
  },
  {
    id: 'research-notes',
    layer: 'ecosystem',
    title: 'Research Notes',
    blurb: 'Short public research posts.',
    status: 'planned',
    today: ['Raw research in docs/'],
    notYet: ['Notes feed'],
  },
  {
    id: 'donate',
    layer: 'ecosystem',
    title: 'Donations & Sustainability',
    blurb: 'Independent funding until accelerator / production.',
    status: 'early_access',
    today: ['Transparent donate page on this site'],
    notYet: ['Finalized legal vehicle & all payment rails'],
  },
]

export function modulesByLayer(layer: Layer): ModuleDef[] {
  return MODULES.filter((m) => m.layer === layer)
}

export function getModule(id: string): ModuleDef | undefined {
  return MODULES.find((m) => m.id === id)
}

export function countByStatus(): Record<HonestyStatus, number> {
  const out = {} as Record<HonestyStatus, number>
  for (const s of Object.keys(STATUS_LABEL) as HonestyStatus[]) out[s] = 0
  for (const m of MODULES) out[m.status]++
  return out
}

export const PRINCIPLES = [
  'Architecture First',
  'Evidence Driven',
  'Visible Evolution',
  'Single Web Surface',
  'Digital Twin (honest status)',
  'Forward Compatible',
  'Production Oriented',
]

export const PUBLIC_CHANGELOG = [
  {
    ver: '1.0.3',
    date: '2026-07-20',
    added: [
      'Problem/Solution rewrite — delegate work, keep control',
      'Asset continuity audit + strategic dependency map (docs)',
      'Public messaging audit (claim ladder)',
    ],
    fixed: ['Undersized market framing on Landing /problem'],
    known: ['Asset monorepo migration incomplete — do not claim Everything-is-an-Asset as done'],
  },
  {
    ver: '1.0.2',
    date: '2026-07-20',
    added: [
      'Investor-grade home (explain, do not sell)',
      'Guest Session only — removed Founder login default',
      'Evidence public board',
      'Donate total (0 USD) + GRECOITALICO identity / socials',
      'Master logo favicons',
    ],
    fixed: ['Insecure founder-as-default session'],
    known: ['Donation rails partially pending', 'Evidence rows partially static until automation'],
  },
  {
    ver: '1.0.1',
    date: '2026-07-19',
    added: [
      'Digital twin catalog (Product · Technology · Organization · Ecosystem)',
      'Investors / accelerators hub',
      'Developer portal',
      'Donate / sustainability page',
      'Problem, Why, Status pages',
    ],
    fixed: ['Removed prior public surface and AI-template marketing UI'],
    known: ['conrrad.org domain cutover may lag Vercel project', 'Donation rails under founder definition'],
  },
  {
    ver: '1.0.0',
    date: '2026-07-19',
    added: ['Product shell', 'Login preview', 'Roadmap', 'Surface lifecycle'],
    fixed: [],
    known: ['Runtime UI not wired'],
  },
]

export const FAQ = [
  {
    q: 'What problem does CONRRAD solve?',
    a: 'Enterprises can generate AI text; they struggle to delegate AI work without losing authority, evidence, and cost control. CONRRAD is infrastructure for governed AI work — not another chatbot or local-model app.',
  },
  {
    q: 'Are you competing with OpenAI / Ollama / OpenCode?',
    a: 'No. Models are resources (like CPU). CONRRAD aims to govern work that may call many intelligences under policy — who authorized, which model, at what cost, with what evidence.',
  },
  {
    q: 'Is CONRRAD production SaaS today?',
    a: 'No. We are in a Visible Evolution phase: public surface + certified runtime path + frozen planning contracts. We do not claim mass-market product-market fit.',
  },
  {
    q: 'What already works?',
    a: 'CAS architecture specs, scheduler Freeze C0, evidence regenerators, host health on Node-01, Birth package path, Atlas + Demo on conrrad.org, and this Website Canon surface. Execution UIs are still rolling out.',
  },
  {
    q: 'What is the product?',
    a: 'The Citizen — a persistent institutional identity. Atlas and Demo are sibling surfaces. Birth package names are technical aliases only.',
  },
  {
    q: 'Who is the founder?',
    a: 'GRECOITALICO — github.com/GRECOITALICO · LinkedIn · YouTube @ConrradLab · X @CONRRADLAB.',
  },
  {
    q: 'Can I sign in as Founder / Admin?',
    a: 'No. Until institutional identity auth exists, the surface only offers Guest Session (visitor). No privileged demo accounts.',
  },
  {
    q: 'How do you make money?',
    a: 'CAS-4: local Birth stays free. Monetization begins at cloud deploy / institutional attestation. Self-serve billing is not live yet. Optional sustainability donations fund independence until then.',
  },
  {
    q: 'Why sustainability donations?',
    a: 'Optional community funding for documentation, infrastructure, testing, research, and certification. Total received is published (including 0 USD). Donations are never a primary product CTA.',
  },
]
